spring.application.name=final-project-museum
spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://96.9.81.189:6438/postgres
spring.datasource.password=Limping5
app.api.sendgrid=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

spring.security.oauth2.client.registration.google.client-id=${app.google.client-id}
spring.security.oauth2.client.registration.google.client-secret=${app.google.client-secret}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/oauth2/callback/google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://accounts.google.com/o/oauth2/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

#for google oauth playground client id: 407408718192.apps.googleusercontent.com
app.google.client-id=555496583444-6ee0f4fdru9e3r4ukdbr9rrualjvvv11.apps.googleusercontent.com
app.google.client-secret=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

app.frontend.url=http://localhost:3000