spring.application.name=final-project-museum
spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/museum
spring.datasource.password=@#$Twisted_World29)#_
app.api.sendgrid=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
app.url.resetpassword=http://localhost:3000/reset-password?token=
